// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -package queue -source interface.go -destination interface_mock.go -self_package github.com/uber/cadence/common/asyncworkflow/queue
//

// Package queue is a generated GoMock package.
package queue

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	provider "github.com/uber/cadence/common/asyncworkflow/queue/provider"
	types "github.com/uber/cadence/common/types"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetPredefinedQueue mocks base method.
func (m *MockProvider) GetPredefinedQueue(arg0 string) (provider.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPredefinedQueue", arg0)
	ret0, _ := ret[0].(provider.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPredefinedQueue indicates an expected call of GetPredefinedQueue.
func (mr *MockProviderMockRecorder) GetPredefinedQueue(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPredefinedQueue", reflect.TypeOf((*MockProvider)(nil).GetPredefinedQueue), arg0)
}

// GetQueue mocks base method.
func (m *MockProvider) GetQueue(arg0 string, arg1 *types.DataBlob) (provider.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueue", arg0, arg1)
	ret0, _ := ret[0].(provider.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueue indicates an expected call of GetQueue.
func (mr *MockProviderMockRecorder) GetQueue(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueue", reflect.TypeOf((*MockProvider)(nil).GetQueue), arg0, arg1)
}
