// Code generated by MockGen. DO NOT EDIT.
// Source: outbounds.go
//
// Generated by this command:
//
//	mockgen -package rpc -source outbounds.go -destination outbounds_mock.go -self_package github.com/uber/cadence/common/rpc
//

// Package rpc is a generated GoMock package.
package rpc

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "go.uber.org/yarpc/transport/grpc"
	tchannel "go.uber.org/yarpc/transport/tchannel"
)

// MockOutboundsBuilder is a mock of OutboundsBuilder interface.
type MockOutboundsBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockOutboundsBuilderMockRecorder
	isgomock struct{}
}

// MockOutboundsBuilderMockRecorder is the mock recorder for MockOutboundsBuilder.
type MockOutboundsBuilderMockRecorder struct {
	mock *MockOutboundsBuilder
}

// NewMockOutboundsBuilder creates a new mock instance.
func NewMockOutboundsBuilder(ctrl *gomock.Controller) *MockOutboundsBuilder {
	mock := &MockOutboundsBuilder{ctrl: ctrl}
	mock.recorder = &MockOutboundsBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboundsBuilder) EXPECT() *MockOutboundsBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockOutboundsBuilder) Build(arg0 *grpc.Transport, arg1 *tchannel.Transport) (*Outbounds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", arg0, arg1)
	ret0, _ := ret[0].(*Outbounds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockOutboundsBuilderMockRecorder) Build(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockOutboundsBuilder)(nil).Build), arg0, arg1)
}
