package thrift

// Code generated by gowrap. DO NOT EDIT.
// template: ../../templates/thrift.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"

	"go.uber.org/yarpc"

	"github.com/uber/cadence/common/types"
	"github.com/uber/cadence/common/types/mapper/thrift"
)

func (g matchingClient) AddActivityTask(ctx context.Context, ap1 *types.AddActivityTaskRequest, p1 ...yarpc.CallOption) (ap2 *types.AddActivityTaskResponse, err error) {
	err = g.c.AddActivityTask(ctx, thrift.FromMatchingAddActivityTaskRequest(ap1), p1...)
	if err != nil {
		return nil, err
	}
	return &types.AddActivityTaskResponse{}, nil
}

func (g matchingClient) AddDecisionTask(ctx context.Context, ap1 *types.AddDecisionTaskRequest, p1 ...yarpc.CallOption) (ap2 *types.AddDecisionTaskResponse, err error) {
	err = g.c.AddDecisionTask(ctx, thrift.FromMatchingAddDecisionTaskRequest(ap1), p1...)
	if err != nil {
		return nil, err
	}
	return &types.AddDecisionTaskResponse{}, nil
}

func (g matchingClient) CancelOutstandingPoll(ctx context.Context, cp1 *types.CancelOutstandingPollRequest, p1 ...yarpc.CallOption) (err error) {
	err = g.c.CancelOutstandingPoll(ctx, thrift.FromMatchingCancelOutstandingPollRequest(cp1), p1...)
	return thrift.ToError(err)
}

func (g matchingClient) DescribeTaskList(ctx context.Context, mp1 *types.MatchingDescribeTaskListRequest, p1 ...yarpc.CallOption) (dp1 *types.DescribeTaskListResponse, err error) {
	response, err := g.c.DescribeTaskList(ctx, thrift.FromMatchingDescribeTaskListRequest(mp1), p1...)
	return thrift.ToMatchingDescribeTaskListResponse(response), thrift.ToError(err)
}

func (g matchingClient) GetTaskListsByDomain(ctx context.Context, gp1 *types.GetTaskListsByDomainRequest, p1 ...yarpc.CallOption) (gp2 *types.GetTaskListsByDomainResponse, err error) {
	response, err := g.c.GetTaskListsByDomain(ctx, thrift.FromMatchingGetTaskListsByDomainRequest(gp1), p1...)
	return thrift.ToMatchingGetTaskListsByDomainResponse(response), thrift.ToError(err)
}

func (g matchingClient) ListTaskListPartitions(ctx context.Context, mp1 *types.MatchingListTaskListPartitionsRequest, p1 ...yarpc.CallOption) (lp1 *types.ListTaskListPartitionsResponse, err error) {
	response, err := g.c.ListTaskListPartitions(ctx, thrift.FromMatchingListTaskListPartitionsRequest(mp1), p1...)
	return thrift.ToMatchingListTaskListPartitionsResponse(response), thrift.ToError(err)
}

func (g matchingClient) PollForActivityTask(ctx context.Context, mp1 *types.MatchingPollForActivityTaskRequest, p1 ...yarpc.CallOption) (mp2 *types.MatchingPollForActivityTaskResponse, err error) {
	response, err := g.c.PollForActivityTask(ctx, thrift.FromMatchingPollForActivityTaskRequest(mp1), p1...)
	return thrift.ToMatchingPollForActivityTaskResponse(response), thrift.ToError(err)
}

func (g matchingClient) PollForDecisionTask(ctx context.Context, mp1 *types.MatchingPollForDecisionTaskRequest, p1 ...yarpc.CallOption) (mp2 *types.MatchingPollForDecisionTaskResponse, err error) {
	response, err := g.c.PollForDecisionTask(ctx, thrift.FromMatchingPollForDecisionTaskRequest(mp1), p1...)
	return thrift.ToMatchingPollForDecisionTaskResponse(response), thrift.ToError(err)
}

func (g matchingClient) QueryWorkflow(ctx context.Context, mp1 *types.MatchingQueryWorkflowRequest, p1 ...yarpc.CallOption) (mp2 *types.MatchingQueryWorkflowResponse, err error) {
	response, err := g.c.QueryWorkflow(ctx, thrift.FromMatchingQueryWorkflowRequest(mp1), p1...)
	return thrift.ToMatchingQueryWorkflowResponse(response), thrift.ToError(err)
}

func (g matchingClient) RefreshTaskListPartitionConfig(ctx context.Context, mp1 *types.MatchingRefreshTaskListPartitionConfigRequest, p1 ...yarpc.CallOption) (mp2 *types.MatchingRefreshTaskListPartitionConfigResponse, err error) {
	return nil, thrift.ToError(&types.BadRequestError{Message: "Feature not supported on TChannel"})
}

func (g matchingClient) RespondQueryTaskCompleted(ctx context.Context, mp1 *types.MatchingRespondQueryTaskCompletedRequest, p1 ...yarpc.CallOption) (err error) {
	err = g.c.RespondQueryTaskCompleted(ctx, thrift.FromMatchingRespondQueryTaskCompletedRequest(mp1), p1...)
	return thrift.ToError(err)
}

func (g matchingClient) UpdateTaskListPartitionConfig(ctx context.Context, mp1 *types.MatchingUpdateTaskListPartitionConfigRequest, p1 ...yarpc.CallOption) (mp2 *types.MatchingUpdateTaskListPartitionConfigResponse, err error) {
	return nil, thrift.ToError(&types.BadRequestError{Message: "Feature not supported on TChannel"})
}
