// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: uber/cadence/sharddistributor/v1/executor.proto

package sharddistributorv1

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// ShardDistributorExecutorAPIYARPCClient is the YARPC client-side interface for the ShardDistributorExecutorAPI service.
type ShardDistributorExecutorAPIYARPCClient interface {
	Heartbeat(context.Context, *HeartbeatRequest, ...yarpc.CallOption) (*HeartbeatResponse, error)
}

func newShardDistributorExecutorAPIYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) ShardDistributorExecutorAPIYARPCClient {
	return &_ShardDistributorExecutorAPIYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.cadence.sharddistributor.v1.ShardDistributorExecutorAPI",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewShardDistributorExecutorAPIYARPCClient builds a new YARPC client for the ShardDistributorExecutorAPI service.
func NewShardDistributorExecutorAPIYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) ShardDistributorExecutorAPIYARPCClient {
	return newShardDistributorExecutorAPIYARPCClient(clientConfig, nil, options...)
}

// ShardDistributorExecutorAPIYARPCServer is the YARPC server-side interface for the ShardDistributorExecutorAPI service.
type ShardDistributorExecutorAPIYARPCServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
}

type buildShardDistributorExecutorAPIYARPCProceduresParams struct {
	Server      ShardDistributorExecutorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildShardDistributorExecutorAPIYARPCProcedures(params buildShardDistributorExecutorAPIYARPCProceduresParams) []transport.Procedure {
	handler := &_ShardDistributorExecutorAPIYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.cadence.sharddistributor.v1.ShardDistributorExecutorAPI",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Heartbeat",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.Heartbeat,
							NewRequest:  newShardDistributorExecutorAPIServiceHeartbeatYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildShardDistributorExecutorAPIYARPCProcedures prepares an implementation of the ShardDistributorExecutorAPI service for YARPC registration.
func BuildShardDistributorExecutorAPIYARPCProcedures(server ShardDistributorExecutorAPIYARPCServer) []transport.Procedure {
	return buildShardDistributorExecutorAPIYARPCProcedures(buildShardDistributorExecutorAPIYARPCProceduresParams{Server: server})
}

// FxShardDistributorExecutorAPIYARPCClientParams defines the input
// for NewFxShardDistributorExecutorAPIYARPCClient. It provides the
// paramaters to get a ShardDistributorExecutorAPIYARPCClient in an
// Fx application.
type FxShardDistributorExecutorAPIYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxShardDistributorExecutorAPIYARPCClientResult defines the output
// of NewFxShardDistributorExecutorAPIYARPCClient. It provides a
// ShardDistributorExecutorAPIYARPCClient to an Fx application.
type FxShardDistributorExecutorAPIYARPCClientResult struct {
	fx.Out

	Client ShardDistributorExecutorAPIYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxShardDistributorExecutorAPIYARPCClient provides a ShardDistributorExecutorAPIYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorExecutorAPIYARPCClient("service-name"),
//	  ...
//	)
func NewFxShardDistributorExecutorAPIYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxShardDistributorExecutorAPIYARPCClientParams) FxShardDistributorExecutorAPIYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxShardDistributorExecutorAPIYARPCClientResult{
			Client: newShardDistributorExecutorAPIYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxShardDistributorExecutorAPIYARPCProceduresParams defines the input
// for NewFxShardDistributorExecutorAPIYARPCProcedures. It provides the
// paramaters to get ShardDistributorExecutorAPIYARPCServer procedures in an
// Fx application.
type FxShardDistributorExecutorAPIYARPCProceduresParams struct {
	fx.In

	Server      ShardDistributorExecutorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxShardDistributorExecutorAPIYARPCProceduresResult defines the output
// of NewFxShardDistributorExecutorAPIYARPCProcedures. It provides
// ShardDistributorExecutorAPIYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxShardDistributorExecutorAPIYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxShardDistributorExecutorAPIYARPCProcedures provides ShardDistributorExecutorAPIYARPCServer procedures to an Fx application.
// It expects a ShardDistributorExecutorAPIYARPCServer to be present in the container.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorExecutorAPIYARPCProcedures(),
//	  ...
//	)
func NewFxShardDistributorExecutorAPIYARPCProcedures() interface{} {
	return func(params FxShardDistributorExecutorAPIYARPCProceduresParams) FxShardDistributorExecutorAPIYARPCProceduresResult {
		return FxShardDistributorExecutorAPIYARPCProceduresResult{
			Procedures: buildShardDistributorExecutorAPIYARPCProcedures(buildShardDistributorExecutorAPIYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: ShardDistributorExecutorAPIReflectionMeta,
		}
	}
}

// ShardDistributorExecutorAPIReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var ShardDistributorExecutorAPIReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.cadence.sharddistributor.v1.ShardDistributorExecutorAPI",
	FileDescriptors: yarpcFileDescriptorClosure5aab034437d08cca,
}

type _ShardDistributorExecutorAPIYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_ShardDistributorExecutorAPIYARPCCaller) Heartbeat(ctx context.Context, request *HeartbeatRequest, options ...yarpc.CallOption) (*HeartbeatResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Heartbeat", request, newShardDistributorExecutorAPIServiceHeartbeatYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*HeartbeatResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorExecutorAPIServiceHeartbeatYARPCResponse, responseMessage)
	}
	return response, err
}

type _ShardDistributorExecutorAPIYARPCHandler struct {
	server ShardDistributorExecutorAPIYARPCServer
}

func (h *_ShardDistributorExecutorAPIYARPCHandler) Heartbeat(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *HeartbeatRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*HeartbeatRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorExecutorAPIServiceHeartbeatYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Heartbeat(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newShardDistributorExecutorAPIServiceHeartbeatYARPCRequest() proto.Message {
	return &HeartbeatRequest{}
}

func newShardDistributorExecutorAPIServiceHeartbeatYARPCResponse() proto.Message {
	return &HeartbeatResponse{}
}

var (
	emptyShardDistributorExecutorAPIServiceHeartbeatYARPCRequest  = &HeartbeatRequest{}
	emptyShardDistributorExecutorAPIServiceHeartbeatYARPCResponse = &HeartbeatResponse{}
)

var yarpcFileDescriptorClosure5aab034437d08cca = [][]byte{
	// uber/cadence/sharddistributor/v1/executor.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x8f, 0xd2, 0x40,
		0x14, 0xb5, 0xa0, 0x9b, 0x70, 0x49, 0xd6, 0x32, 0x59, 0x97, 0x0a, 0xbb, 0x91, 0xf0, 0x44, 0x48,
		0x6c, 0xa5, 0xbc, 0x18, 0x7d, 0x30, 0x75, 0xdb, 0xc0, 0xac, 0x6b, 0x35, 0x2d, 0xbb, 0x51, 0x13,
		0x43, 0x06, 0x3a, 0x61, 0x89, 0x4b, 0x8b, 0x9d, 0x69, 0x23, 0xc6, 0x37, 0xfd, 0x07, 0xc6, 0xff,
		0x6b, 0xfa, 0xc1, 0x02, 0x2d, 0x06, 0xd9, 0xb7, 0xf6, 0x9e, 0x7b, 0xce, 0xbd, 0x73, 0xce, 0x64,
		0x40, 0x09, 0x46, 0xd4, 0x57, 0xc6, 0xc4, 0xa1, 0xee, 0x98, 0x2a, 0xec, 0x9a, 0xf8, 0x8e, 0x33,
		0x65, 0xdc, 0x9f, 0x8e, 0x02, 0xee, 0xf9, 0x4a, 0xd8, 0x51, 0xe8, 0x37, 0x3a, 0x8e, 0xbe, 0xe5,
		0xb9, 0xef, 0x71, 0x0f, 0x35, 0x22, 0x82, 0x9c, 0x12, 0xe4, 0x2c, 0x41, 0x0e, 0x3b, 0xcd, 0x3f,
		0x45, 0x10, 0xfb, 0x94, 0xf8, 0x7c, 0x44, 0x09, 0xb7, 0xe8, 0xd7, 0x80, 0x32, 0x8e, 0x4e, 0xa0,
		0xe4, 0x92, 0x19, 0x65, 0x73, 0x32, 0xa6, 0x92, 0xd0, 0x10, 0x5a, 0x25, 0x6b, 0x55, 0x40, 0x4f,
		0xa0, 0xbc, 0x1c, 0x33, 0x9c, 0x3a, 0x52, 0x21, 0xc6, 0x61, 0x59, 0xc2, 0x0e, 0xea, 0xc3, 0x01,
		0xe3, 0x84, 0x07, 0x4c, 0x2a, 0x36, 0x84, 0xd6, 0xa1, 0xfa, 0x4c, 0xde, 0xb5, 0x86, 0x6c, 0xa4,
		0x6c, 0x3b, 0xe6, 0x59, 0x29, 0x1f, 0xfd, 0x80, 0xa3, 0xb8, 0x7b, 0x98, 0xfc, 0x0f, 0x7d, 0x3a,
		0xf7, 0x7c, 0xce, 0xa4, 0xfb, 0x8d, 0x62, 0xab, 0xac, 0x9e, 0xef, 0xd6, 0xcd, 0x1e, 0x4d, 0xb6,
		0xa3, 0xa6, 0x74, 0x4a, 0x22, 0x66, 0xb8, 0xdc, 0x5f, 0x58, 0x88, 0xe5, 0x80, 0xda, 0x77, 0xa8,
		0xfe, 0xa3, 0x1d, 0x89, 0x50, 0xfc, 0x42, 0x17, 0xa9, 0x37, 0xd1, 0x27, 0xc2, 0xf0, 0x20, 0x24,
		0x37, 0x01, 0x8d, 0xfd, 0x28, 0xab, 0xdd, 0xdd, 0xbb, 0xe5, 0xb4, 0xad, 0x44, 0xe1, 0x45, 0xe1,
		0xb9, 0xd0, 0x5c, 0x40, 0x25, 0x87, 0x23, 0xe3, 0xd6, 0x58, 0x21, 0x36, 0xf6, 0xe9, 0x7e, 0x43,
		0x96, 0xae, 0x9e, 0x02, 0x24, 0xae, 0xde, 0x78, 0x24, 0xc9, 0x4f, 0xb0, 0x4a, 0x71, 0xe5, 0xc2,
		0x23, 0x4e, 0xf3, 0x67, 0x01, 0x2a, 0x6b, 0xbe, 0xb1, 0xb9, 0xe7, 0x32, 0x8a, 0x42, 0xa8, 0x24,
		0x24, 0xc2, 0xd8, 0x74, 0xe2, 0xce, 0xa8, 0xcb, 0xa3, 0x35, 0xa2, 0x1c, 0xf0, 0x5e, 0x39, 0x24,
		0x7a, 0xc9, 0x62, 0xda, 0x4a, 0x2b, 0x89, 0x41, 0x64, 0x99, 0x72, 0x2d, 0x84, 0x47, 0x5b, 0x5b,
		0xb7, 0x44, 0xd0, 0xdb, 0x8c, 0xa0, 0xf3, 0x9f, 0xee, 0xac, 0x94, 0xd7, 0x03, 0xf8, 0x0c, 0x0f,
		0x33, 0x28, 0x3a, 0xcf, 0xd8, 0xaf, 0xee, 0x1e, 0xb0, 0x62, 0x6f, 0x66, 0xd0, 0xfe, 0x25, 0xc0,
		0xe1, 0xe6, 0xa5, 0x47, 0x75, 0xa8, 0x1a, 0x1f, 0x8c, 0xb3, 0xcb, 0xc1, 0x3b, 0x6b, 0x68, 0x0f,
		0xb4, 0xc1, 0xa5, 0x3d, 0xc4, 0xe6, 0x95, 0x76, 0x81, 0x75, 0xf1, 0x1e, 0xaa, 0xc1, 0x71, 0x16,
		0xd4, 0xce, 0x06, 0xf8, 0xca, 0x10, 0x05, 0x74, 0x02, 0x52, 0x16, 0xd3, 0x2d, 0x0d, 0x9b, 0xd8,
		0xec, 0x89, 0x85, 0x6d, 0xb2, 0x31, 0x6a, 0xe8, 0x62, 0xb1, 0xfd, 0x0a, 0xca, 0x6b, 0x37, 0x04,
		0x49, 0x70, 0x64, 0xf7, 0x35, 0x4b, 0xcf, 0xcf, 0x3f, 0x06, 0xb4, 0x81, 0x58, 0x86, 0xa6, 0x7f,
		0x14, 0x85, 0xb6, 0x09, 0x62, 0xf6, 0x8c, 0xe8, 0x14, 0x1e, 0x6b, 0xb6, 0x8d, 0x7b, 0xe6, 0x5b,
		0xc3, 0x1c, 0xe4, 0xa5, 0xea, 0x50, 0xcd, 0xc3, 0xa9, 0x9e, 0xfa, 0x5b, 0x80, 0x7a, 0xbc, 0x91,
		0xbe, 0x32, 0x72, 0xe9, 0x93, 0xf6, 0x1e, 0x23, 0x0e, 0xa5, 0xdb, 0xbb, 0x84, 0xd4, 0xfd, 0x1f,
		0x80, 0x5a, 0xf7, 0x0e, 0x97, 0xf5, 0xf5, 0x9b, 0x4f, 0x78, 0x32, 0xe5, 0xd7, 0xc1, 0x48, 0x1e,
		0x7b, 0xb3, 0xcd, 0x57, 0x58, 0x9e, 0x50, 0x57, 0x89, 0x5f, 0xdb, 0x6d, 0x0f, 0xf2, 0xcb, 0x6c,
		0x2d, 0xec, 0x8c, 0x0e, 0xe2, 0xee, 0xee, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xc8, 0xec,
		0x23, 0xce, 0x05, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) ShardDistributorExecutorAPIYARPCClient {
			return NewShardDistributorExecutorAPIYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
