// Code generated by MockGen. DO NOT EDIT.
// Source: notifier.go
//
// Generated by this command:
//
//	mockgen -package events -source notifier.go -destination notifier_mock.go -self_package github.com/uber/cadence/service/history/events
//

// Package events is a generated GoMock package.
package events

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	definition "github.com/uber/cadence/common/definition"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// NotifyNewHistoryEvent mocks base method.
func (m *MockNotifier) NotifyNewHistoryEvent(event *Notification) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyNewHistoryEvent", event)
}

// NotifyNewHistoryEvent indicates an expected call of NotifyNewHistoryEvent.
func (mr *MockNotifierMockRecorder) NotifyNewHistoryEvent(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyNewHistoryEvent", reflect.TypeOf((*MockNotifier)(nil).NotifyNewHistoryEvent), event)
}

// Start mocks base method.
func (m *MockNotifier) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockNotifierMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockNotifier)(nil).Start))
}

// Stop mocks base method.
func (m *MockNotifier) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockNotifierMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockNotifier)(nil).Stop))
}

// UnwatchHistoryEvent mocks base method.
func (m *MockNotifier) UnwatchHistoryEvent(identifier definition.WorkflowIdentifier, subscriberID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnwatchHistoryEvent", identifier, subscriberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnwatchHistoryEvent indicates an expected call of UnwatchHistoryEvent.
func (mr *MockNotifierMockRecorder) UnwatchHistoryEvent(identifier, subscriberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnwatchHistoryEvent", reflect.TypeOf((*MockNotifier)(nil).UnwatchHistoryEvent), identifier, subscriberID)
}

// WatchHistoryEvent mocks base method.
func (m *MockNotifier) WatchHistoryEvent(identifier definition.WorkflowIdentifier) (string, chan *Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchHistoryEvent", identifier)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(chan *Notification)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WatchHistoryEvent indicates an expected call of WatchHistoryEvent.
func (mr *MockNotifierMockRecorder) WatchHistoryEvent(identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchHistoryEvent", reflect.TypeOf((*MockNotifier)(nil).WatchHistoryEvent), identifier)
}
